#===============================================================================
# Copyright 2024 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#===============================================================================

name: CI
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - main
  workflow_dispatch:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref_name }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  DPCTL_VERSION: 0.18.1
  DPNP_VERSION: 0.16.0
  DPCTL_PY_VERSIONS: '3.9\|3.11'

jobs:
  sklearn_lnx:
    strategy:
      fail-fast: false
      matrix:
        include:
          - PYTHON_VERSION: "3.10"
            SKLEARN_VERSION: "1.2"
    name: LinuxNightly/pip Python${{ matrix.PYTHON_VERSION }}_Sklearn${{ matrix.SKLEARN_VERSION }}
    runs-on: ubuntu-24.04
    timeout-minutes: 120

    steps:
      - name: Checkout Scikit-learn-intelex
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}  
      - name: Get run ID of "Nightly-build" workflow
        id: get-run-id
        run: |
          OTHER_REPO="uxlfoundation/oneDAL"
          WF_NAME="Nightly-build"
          JQ_QUERY='map(select(.event == "workflow_dispatch" or .event == "schedule")) | .[0].databaseId'
          RUN_ID=`gh run --repo ${OTHER_REPO} list --workflow "${WF_NAME}" --json databaseId,event --status success --jq "${JQ_QUERY}"`
          echo "Detected latest run id of ${RUN_ID} for workflow ${WF_NAME}"
          echo "run-id=${RUN_ID}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Download oneDAL build artifact
        uses: actions/download-artifact@v4
        with:
          name: __release_lnx
          github-token: ${{ github.token }}
          repository: uxlfoundation/oneDAL
          run-id: ${{ steps.get-run-id.outputs.run-id }}
          path: ./__release_lnx
      - name: Download oneDAL environment artifact
        uses: actions/download-artifact@v4
        with:
          name: oneDAL_env
          github-token: ${{ github.token }}
          repository: uxlfoundation/oneDAL
          run-id: ${{ steps.get-run-id.outputs.run-id }}
          path: .ci/env
      - name: Set Environment Variables
        id: set-env
        run: |
          # Disable SPMD testing
          echo "NO_DIST=1" >> "$GITHUB_ENV"
          # Determine dpctl support
          DPCFLAG="0"
          if [ $(echo ${{ matrix.PYTHON_VERSION }} | grep '${{ env.DPCTL_PY_VERSIONS }}') ]; then DPCFLAG=''; fi
          echo "DPCFLAG=${DPCFLAG}" >> "$GITHUB_OUTPUT"
          # enable coverage report generation
          echo "COVERAGE_RCFILE=$(readlink -f .coveragerc)" >> "$GITHUB_ENV"
      - name: apt-get
        run: sudo apt-get update && sudo apt-get install -y clang-format
      - name: dpcpp installation
        run: |
          # This CI system yields oneAPI dependencies from the oneDAL repository
          bash .ci/env/apt.sh dpcpp
      - name: describe system
        run: |
          source /opt/intel/oneapi/setvars.sh
          bash .ci/scripts/describe_system.sh
      - name: Install develop requirements
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r dependencies-dev
          pip list
      - name: Build daal4py/sklearnex
        run: |
          source venv/bin/activate
          source .github/scripts/activate_components.sh ${{ steps.set-env.outputs.DPCFLAG }}
          python setup.py install --single-version-externally-managed --record=record.txt
      - name: Install testing requirements
        run: |
          source venv/bin/activate
          source .github/scripts/activate_components.sh
          bash .ci/scripts/setup_sklearn.sh ${{ matrix.SKLEARN_VERSION }}
          pip install --upgrade -r requirements-test.txt
          pip install $(python .ci/scripts/get_compatible_scipy_version.py ${{ matrix.SKLEARN_VERSION }}) pyyaml
          if [ "${{ steps.set-env.outputs.DPCFLAG }}" == "" ]; then pip install dpctl==${{ env.DPCTL_VERSION }} dpnp==${{ env.DPNP_VERSION }}; fi
          pip list
      - name: Sklearnex testing
        run: |
          source venv/bin/activate
          source .github/scripts/activate_components.sh
          export COVERAGE_FILE=$(pwd)/.coverage.sklearnex
          cd .ci
          ../conda-recipe/run_test.sh
      - name: Sklearn testing
        run: |
          source venv/bin/activate
          source .github/scripts/activate_components.sh
          export COVERAGE_FILE=$(pwd)/.coverage.sklearn
          if [ "${{ steps.set-env.outputs.DPCFLAG }}" == "" ]; then export CPU=cpu; fi
          bash .ci/scripts/run_sklearn_tests.sh $CPU
      - name: Archive coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage_lnx_Py${{ matrix.PYTHON_VERSION }}_${{ matrix.SKLEARN_VERSION }}
          path: |
             .coverage.sklearn
             .coverage.sklearnex
          include-hidden-files: true
      - name: Sklearn testing [preview]
        run: |
          source venv/bin/activate
          source .github/scripts/activate_components.sh
          if [ "${{ steps.set-env.outputs.DPCFLAG }}" == "" ]; then export CPU=cpu; fi
          export SKLEARNEX_PREVIEW='YES'
          bash .ci/scripts/run_sklearn_tests.sh $CPU
